### ISSUE TITLE
Puppet Style Guide re: hash rockets, indentation should be followed

### ISSUE THREAD

**Issue by moutons** [russCloak/SublimePuppet#13]
The Style Guide has some stuff to say about [Arrow Alignment and indenting](https://docs.puppetlabs.com/guides/style_guide.html#arrow-alignment); [Spacing, Indentation, and Whitespace](https://docs.puppetlabs.com/guides/style_guide.html#spacing-indentation-and-whitespace); among other things. Two of those are 
- Indentation should be 2 spaces, and 
- hash rockets in a resource's attribute/value list should be aligned according to the guide

**Comment by frizop** [comment]
Just use the puppet linter, on save it'll pop up a nice little example of what's failing or working.

**Comment by moutons** [comment]
:zombie: I honestly don't recall the specifics here as I don't use Sublime or Puppet anymore, but I suspect it was an issue with SublimePuppet's style not following the linter's at the time ... over two years ago ...

**Comment by petems** [comment]
@moutons Yeah, it would be ideal if the setup auto-aligned the hashrockes like `puppet-lint -f` does, but I'm not sure how to do that. Even the Atom auto-alignment doesnt work that well..
