### ISSUE TITLE
Support EPP files as Puppet?

### ISSUE THREAD

**Issue by ardrigh** [russCloak/SublimePuppet#28]
I have been using this package with ST3 for a while, so thanks for your work :+1: 

I am using this package installed for ST3 with the "A File Icon" package, which appears to use this package to define what "Puppet syntax" files are, to the display a file icon.

This package sets the file extension .pp for Puppet syntax files, but does not include .epp for the newer Embedded Puppet templates.

Is it possible to add the .epp file extension to get the Puppet syntax highlighting and thus a nice file icon?

**Comment by petems** [comment]
Should be fixed for you now 😄

**Comment by petems** [comment]
Added another issue to improve it in the future 👍

**Comment by petems** [comment]
https://github.com/russCloak/SublimePuppet/issues/33
