### ISSUE TITLE
Syntax highlighting for puppet resources should be dependent on colon not on quotes

### ISSUE THREAD

**Issue by dhollinger** [russCloak/SublimePuppet#6]
Resource highlighting should be dependent on a colon existing after resource title declaration, not based on quotes. This is due to puppet-lint giving warnings when you encase a variable by itself in quotes:

    package { "${saint::saint_deps}:
        ensure => latest,
    }

Error: String containing only a variable.

Good colors, bad syntax:
![image of bad syntax]
(https://raw.githubusercontent.com/EagleDelta2/pictures/master/Screen%20Shot%202014-07-11%20at%2010.36.23%20AM.png) 

Bad colors, good syntax:
![image of good syntax]
(https://raw.githubusercontent.com/EagleDelta2/pictures/master/Screen%20Shot%202014-07-11%20at%2010.37.09%20AM.png)

**Comment by petems** [comment]
It's something to do with this regex in SymbolList(resource)...

```
<key>symbolTransformation</key>
<string>s/^\s*(\w+)\s*{\s*['"](.*)['"]:/  \u$1["$2"]/</string>
```

**Comment by petems** [comment]
Only took 2 years to figure out :sweat: 

The screenshot images are now broken (github fail) but I think this is what the original issue was from memory:

Before:
<img width="237" alt="screenshot 2016-02-15 11 00 14" src="https://cloud.githubusercontent.com/assets/1064715/13046929/8ece6090-d3d3-11e5-855e-dbd63d801598.png">

After:
<img width="249" alt="screenshot 2016-02-15 11 01 44" src="https://cloud.githubusercontent.com/assets/1064715/13046935/90b6c492-d3d3-11e5-8f95-5628ec746e9f.png">

Hopefully this fixes the issue for you! :smile:

**Comment by dhollinger** [comment]
Awesome, Thanks!

I probably broke the image links when I changed my github username
